# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imgsrc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
